require "date"
require "time"
require "httparty"
require "json"

desc "运行"
task :run do
  system "bundle exec jekyll serve --incremental --port 10226"
end

desc "部署"
task :deploy do
  git_url = "https://github.com/ourai/knosys.git"
  git_branch = "gh-pages"
  dir_name = "knosys"

  dir = "../../../.tmp/#{dir_name}"

  unless FileTest.directory?("../.tmp")
    system "mkdir ../../.tmp"
  end

  unless FileTest.directory?(dir)
    system "mkdir #{dir}"

    cd dir do
      system "git init"
      system "git remote add origin #{git_url}"
      system "git fetch"
      system "git checkout #{git_branch}"
    end
  else
    cd dir do
      # system "git reset --hard HEAD"
      system "git pull origin #{git_branch}"
    end
  end

  system "bundle exec jekyll clean"
  system "JEKYLL_ENV=production bundle exec jekyll build -d #{dir}"
  
  cd dir do
    current_time = Time.now.strftime("%Y-%m-%d %H:%M:%S")

    system "rm -rf CNAME && touch .nojekyll"
    system "git add -A"
    system "git commit -m 'build: generate on #{current_time}'"
    system "git push origin #{git_branch}"
  end
end
