title: KnoSys
description: 开放的知识管理工具
keywords:

port: 10226

collections:
  pages:
    output: true
    permalink: /:path/
  knosys:
    output: true
    permalink: /:path/

# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - .vscode
  - node_modules
  - build
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - package-lock.json
  - CNAME
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: ksio/default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: ksio/page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: ksio/post
      css:
        - ksio/pages/post
      js:
        - ksio/initializers/time
        - ksio/initializers/lazyload
      author:
        name: 欧雷
        email: ourairyu@gmail.com
        uri: https://ourai.ws/
        slug: ourai
        twitter: ourairyu
      siblings: true
  - scope:
      path: ""
      type: knosys
    values:
      layout: ksio/doc
      css:
        - ksio/pages/post
        - ksio/pages/doc
      js:
        - ksio/initializers/time
        - ksio/initializers/lazyload
      repo: cookbook



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts:
    category: archive/category
    tag: archive/tag
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
    year: "/archives/:year/"

# Jekyll Feed
feed:
  path: atom.xml
name: KnoSys
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: https://ourai.ws/
  twitter: ourairyu
github:
  url: https://knosysio.github.io



# =====
# Customized configurations
# =====

ksio:
  brand:
    color: "#0871ab"
  navs:
    - text: API
      url: /apis/config/
    - text: 关于
      children:
        - text: 作者
          url: https://linxoid.com/ourai/
        - text: GitHub
          url: https://github.com/ourai/knosys
  links:
    - text: OOSS
      url: https://oss.ourai.ws/
    - text: QiiDB
      url: https://qiidb.github.io/
  modules:
    social:
      share: true
